# Generated by Django 5.2.17 on 2026-08-22 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("resource_type", models.CharField(default="Guide", max_length=50)),
                ("category", models.CharField(default="General", max_length=80)),
                ("link", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("level", models.CharField(default="Beginner", max_length=50)),
                ("duration", models.CharField(default="Flexible", max_length=50)),
                ("summary", models.TextField(blank=True, default="")),
                ("steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Frontend", "Frontend"),
                    ("Backend", "Backend"),
                    ("DevOps", "DevOps"),
                    ("AI", "AI"),
                    ("Design", "Design"),
                    ("Productivity", "Productivity"),
                    ("General", "General"),
                ],
                default="General",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Completed", "Completed"),
                    ("On Hold", "On Hold"),
                ],
                default="In Progress",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("tag", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tool_name")},
            },
        ),
    ]
