# Generated by Django 5.2.17 on 2026-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_resource_workflow_project_category_project_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("tag", models.CharField(default="General", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend"),
                            ("Backend", "Backend"),
                            ("DevOps", "DevOps"),
                            ("AI", "AI"),
                            ("Design", "Design"),
                            ("Productivity", "Productivity"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("accent", models.CharField(default="cyan", max_length=20)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
