import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../services/api";

export function GlobalSearch({ workspace, files, onOpen, onClose, onFileSaved }) {
  const [query,setQuery]=useState("");
  const [replace,setReplace]=useState("");
  const [caseSensitive,setCaseSensitive]=useState(false);
  const [regex,setRegex]=useState(false);
  const [replaceMode,setReplaceMode]=useState(false);
  const results=useMemo(()=>{if(!workspace||!query)return [];let re;try{re=regex?new RegExp(query,caseSensitive?"g":"gi"):new RegExp(query.replace(/[.*+?^$()|[\\]\\]/g,"\\$&"),caseSensitive?"g":"gi")}catch{return []}const out=[];Object.entries(files||{}).forEach(([path,text])=>String(text).split("\n").forEach((line,i)=>{re.lastIndex=0;let m;while((m=re.exec(line))){out.push({path,line:i+1,text:line.trim(),column:m.index+1,match:m[0]});if(!re.global)break;if(m[0]==="")re.lastIndex++}}));return out.slice(0,500);  },[files,query,regex,caseSensitive,workspace]);
  async function applyReplace(all=false){if(!query||!results.length||!workspace)return;let rx;try{rx=regex?new RegExp(query,caseSensitive?"g":"gi"):new RegExp(query.replace(/[.*+?^$()|[\\]\\]/g,"\\$&"),caseSensitive?"g":"gi")}catch{return}const targets=all?[...new Set(results.map(r=>r.path))]:[results[0].path];if(all&&!window.confirm(`Replace ${results.length} matches in ${targets.length} files?`))return;let revision=workspace.revision;const next={...files};try{for(const path of targets){const content=String(next[path]||"").replace(rx,replace);const resp=await apiFetch(`/ide/workspaces/${workspace.id}/files/`,{method:"POST",body:JSON.stringify({path,content,revision})});const d=await resp.json();if(!resp.ok)throw Error(d.error||d.detail||("Replace failed for "+path));next[path]=content;revision=d.revision??revision;onFileSaved?.(path,content,revision)}setQuery("");}catch(e){alert(e.message||"Replace failed");}}
  return <div className="dos-search-panel"><div className="dos-search-head"><strong>SEARCH</strong><span className="dos-search-count">{results.length}</span><button onClick={onClose}>×</button></div><div className="dos-search-input"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search in workspace…"/><button className={caseSensitive?"on":""} onClick={()=>setCaseSensitive(x=>!x)}>Aa</button><button className={regex?"on":""} onClick={()=>setRegex(x=>!x)}>.*</button></div><div className="dos-search-tabs"><button className={!replaceMode?"active":""} onClick={()=>setReplaceMode(false)}>Find</button><button className={replaceMode?"active":""} onClick={()=>setReplaceMode(true)}>Replace</button></div>{replaceMode&&<div className="dos-search-input"><span>↪</span><input value={replace} onChange={e=>setReplace(e.target.value)} placeholder="Replace with…"/><button onClick={()=>applyReplace(false)}>Replace</button><button onClick={()=>applyReplace(true)}>All</button></div>}<div className="dos-search-meta">{results.length} result{results.length===1?"":"s"}</div><div className="dos-search-results">{results.map((r,i)=><button key={`${r.path}:${r.line}:${i}`} onClick={()=>onOpen(r.path,r.line,r.column)}><strong>{r.path}</strong><span><b>{r.line}</b> {r.text||"(empty line)"}</span></button>)}</div></div>
}

export function ProblemsPanel({ diagnostics=[], onClose, onOpen }) {
 return <section className="dos-problems"><header><strong>PROBLEMS</strong><span>{diagnostics.length}</span><button onClick={onClose}>×</button></header>{diagnostics.length?<div>{diagnostics.map((d,i)=><button key={i} onClick={()=>onOpen?.(d)}><i className={d.severity||"error"}/><span><b>{d.path||"Current file"}</b><small>Line {d.line||1}:{d.column||1} — {d.message}</small></span></button>)}</div>:<p>✓ No problems detected.</p>}</section>
}

export function RunCenter({workspace,files,onClose}) {
 const [capabilities,setCapabilities]=useState(null),[capState,setCapState]=useState("loading"),[capError,setCapError]=useState("");
 const [command,setCommand]=useState("npm run build"),[running,setRunning]=useState(false),[output,setOutput]=useState(""),[exitCode,setExitCode]=useState(null),[duration,setDuration]=useState(0),[tab,setTab]=useState("terminal"),[processes,setProcesses]=useState([]),[busy,setBusy]=useState(false);
 const runtimes=capabilities?.runtimes||{};
 const runtimeFor=cmd=>/^python(\s|$)/.test(cmd)&&!runtimes.python?.available&&runtimes.python3?.available?"python3":/^node(\s|$)/.test(cmd)&&!runtimes.node?.available?"node":cmd.split(/\s+/)[0];
 const presets=[["Build","npm run build"],["Test","npm test"],["Lint","npm run lint"],["Python","python main.py"],["Django","python manage.py check"],["TypeScript","npx tsc --noEmit"]];
 useEffect(()=>{let alive=true;apiFetch("/ide/capabilities/").then(async r=>{const d=await r.json();if(!r.ok||d.status!=="ready")throw Error(d.error||"Runner capability handshake unavailable");if(alive){setCapabilities(d.runner);setCapState("ready")}}).catch(e=>{if(alive){setCapState("degraded");setCapError(e.message)}});return()=>{alive=false}},[]);
 const adapt=cmd=>/^python(\s|$)/.test(cmd)&&!runtimes.python?.available&&runtimes.python3?.available?cmd.replace(/^python(?=\s|$)/,"python3"):cmd;
 async function execute(){if(!workspace||running||!command.trim())return;if(capState!=="ready"||!capabilities?.operations?.execute){setOutput("[CAPABILITY] Secure execution is unavailable. No command was sent.");return}const effective=adapt(command.trim());setRunning(true);setExitCode(null);setOutput("");setTab("terminal");const started=performance.now();try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/execute/`,{method:"POST",body:JSON.stringify({command:effective,files:files||workspace.files||{}})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||"Secure runner unavailable");setOutput([d.stdout,d.stderr].filter(Boolean).join("\n")||"(no output)");setExitCode(d.exit_code??null);setDuration(d.duration_ms||Math.round(performance.now()-started));}catch(e){setOutput(e.message);setExitCode(-1)}finally{setRunning(false)}}
 async function refreshProcesses(){if(!workspace)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/processes/`);const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Process API unavailable (HTTP ${r.status})`);setProcesses(Array.isArray(d)?d:(d.processes||[]))}catch(e){setOutput(e.message||"Process API unavailable")}finally{setBusy(false)}}
 async function startProcess(){if(!workspace||busy||!command.trim())return;if(capState!=="ready"||!capabilities?.operations?.process){setOutput("[CAPABILITY] Process management is unavailable.");return}setBusy(true);setOutput("");try{const effective=adapt(command.trim());const r=await apiFetch(`/ide/workspaces/${workspace.id}/process/start/`,{method:"POST",body:JSON.stringify({command:effective,files:files||workspace.files||{}})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Process start failed (HTTP ${r.status})`);setOutput([d.stdout,d.stderr].filter(Boolean).join("\n")||`Process ${d.id||""} started.`);setTab("processes");await refreshProcesses()}catch(e){setOutput(e.message||"Process start failed")}finally{setBusy(false)}}
 async function stopProcess(id){if(!workspace||!id)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/process/${encodeURIComponent(id)}/`,{method:"POST"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||d.detail||`Process stop failed (HTTP ${r.status})`);await refreshProcesses()}catch(e){setOutput(e.message||"Process stop failed")}finally{setBusy(false)}}
 useEffect(()=>{refreshProcesses();const t=setInterval(refreshProcesses,4000);return()=>clearInterval(t)},[workspace?.id]);
 return <section className="dos-run-center"><header><div><strong>CODE EXECUTION</strong><small>CAPABILITY-AWARE SECURE RUNTIME</small></div><button onClick={onClose}>×</button></header><div className="dos-run-presets">{presets.map(([name,cmd])=><button key={name} onClick={()=>setCommand(adapt(cmd))} disabled={capState!=="ready"}>{name}</button>)}</div><div className="dos-run-command"><span>›</span><input value={command} onChange={e=>setCommand(e.target.value)}/><button className="dos-run-main" onClick={execute} disabled={running||busy||capState!=="ready"}>{running?"■ Running…":"▶ Run"}</button><button onClick={startProcess} disabled={running||busy||capState!=="ready"}>⚙ Start Process</button></div><div className="dos-run-tabs"><button className={tab==="terminal"?"active":""} onClick={()=>setTab("terminal")}>TERMINAL</button><button className={tab==="processes"?"active":""} onClick={()=>setTab("processes")}>PROCESSES {processes.length}</button><button onClick={refreshProcesses}>↻</button></div>{tab==="terminal"?<div className="dos-run-output"><div className="dos-run-metrics"><span>RUNNER <b>{capState.toUpperCase()}</b></span><span>EXIT <b>{exitCode??"—"}</b></span><span>TIME <b>{duration}ms</b></span><span>SANDBOX <b>{capabilities?.sandbox?.mode||"—"}</b></span></div>{capError&&<div className="dos-run-error">{capError}</div>}<pre>{output||"Ready. Runtime capabilities are negotiated before execution."}</pre></div>:<div className="dos-process-list">{processes.length?processes.map((p,i)=><div className="dos-process" key={p.id||p.process_id||i}><div><b>{p.command||p.name||"process"}</b><small>{p.id||p.process_id} · {p.status||"running"}</small></div><button onClick={()=>stopProcess(p.id||p.process_id)} disabled={busy}>Stop</button></div>):<div className="dos-empty">No active processes.</div>}</div>}<footer><span>🔒 {Object.entries(runtimes).filter(([,v])=>v?.available).map(([k,v])=>`${k} ${v.version||""}`).join(" · ")||"No runtimes detected"}</span><button onClick={()=>setTab("processes")}>Manage processes</button></footer></section>
}
export function DebuggerPanel({workspace,activeFile,onOpen,onClose}) {
 const [session,setSession]=useState(null),[state,setState]=useState("idle"),[breakpoints,setBreakpoints]=useState([]),[expression,setExpression]=useState(""),[result,setResult]=useState(null),[stack,setStack]=useState([]),[variables,setVariables]=useState([]),[output,setOutput]=useState(""),[busy,setBusy]=useState(false);
 async function call(action,extra={}){if(!workspace)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/debug/`,{method:"POST",body:JSON.stringify({action,session_id:session,path:activeFile,...extra,breakpoints})});const d=await r.json();if(!r.ok)throw Error(d.error||"Debugger request failed");setSession(d.session_id||session);setState(d.state||state);setStack(d.stack||[]);setVariables(d.variables||[]);setOutput(d.output||"");setResult(d.result??null);if(d.breakpoints)setBreakpoints(d.breakpoints);}catch(e){setOutput(e.message)}finally{setBusy(false)}}
 function toggleBreakpoint(){if(!activeFile)return;const key=activeFile+":1";setBreakpoints(x=>x.includes(key)?x.filter(v=>v!==key):[...x,key]);}
 return <section className="dos-debugger"><header><div><strong>DEBUGGER</strong><small>ISOLATED RUNTIME · DAP READY</small></div><button onClick={onClose}>×</button></header><div className="dos-debug-toolbar"><button onClick={()=>call("start")} disabled={busy}>▶ Start</button><button onClick={()=>call("continue")} disabled={!session||busy}>Continue</button><button onClick={()=>call("pause")} disabled={!session||busy}>Pause</button><button onClick={()=>call("step_over")} disabled={!session||busy}>Step Over</button><button onClick={()=>call("step_into")} disabled={!session||busy}>Step Into</button><button onClick={()=>call("step_out")} disabled={!session||busy}>Step Out</button><button onClick={()=>call("stop")} disabled={!session||busy}>■</button></div><div className="dos-debug-grid"><div><h4>CALL STACK</h4>{stack.length?stack.map((f,i)=><button key={i} onClick={()=>onOpen?.(f.path,f.line,f.column)}>{f.name||"frame"}<small>{f.path}:{f.line||1}</small></button>):<p>Waiting for a debug session…</p>}</div><div><h4>VARIABLES</h4>{variables.length?variables.map((v,i)=><div className="dos-debug-var" key={i}><b>{v.name}</b><span>{String(v.value??"")}</span></div>):<p>No variables in current scope.</p>}</div><div><h4>BREAKPOINTS</h4><button onClick={toggleBreakpoint}>＋ {activeFile||"current file"} : 1</button>{breakpoints.map((b,i)=><div key={i}>{b}</div>)}</div></div><div className="dos-debug-console"><div><b>DEBUG CONSOLE</b><button onClick={()=>call("evaluate",{expression})} disabled={!session||busy}>Evaluate</button></div><input value={expression} onChange={e=>setExpression(e.target.value)} onKeyDown={e=>e.key==="Enter"&&call("evaluate",{expression})} placeholder="Evaluate expression…"/>{result!==null&&<pre>{typeof result==="string"?result:JSON.stringify(result,null,2)}</pre>}{output&&<pre>{output}</pre>}</div></section>
}

export function PreviewPanel({workspace,onClose}) {
 const [url,setUrl]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function start(){if(!workspace)return;setLoading(true);setError("");try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/preview/start/`,{method:"POST",body:JSON.stringify({framework:workspace.framework||""})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Preview start failed (HTTP ${r.status})`);setUrl(d.public_preview||d.preview_url||d.url||"")}catch(e){setError(e.message||"Preview could not be started")}finally{setLoading(false)}}
 return <div className="dos-preview"><header><strong>LIVE PREVIEW</strong><button onClick={onClose}>×</button></header><div className="dos-preview-toolbar"><button onClick={start}>{loading?"Starting…":"▶ Start Preview"}</button><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Preview path"/><button onClick={()=>url&&window.open(url,"_blank","noopener,noreferrer")}>↗</button></div>{error&&<div className="dos-preview-empty">{error}</div>}{url&&!error&&<div className="dos-preview-empty">Preview process started. Open the preview path in the authenticated Developer OS session.</div>}{!url&&!error&&<div className="dos-preview-empty">Start a workspace preview to launch the configured framework runner.</div>}</div>
}

export function SourceControlPanel({workspace,onClose,onSync}) {
 const [repos,setRepos]=useState([]); const [name,setName]=useState(""); const [selected,setSelected]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("Developer OS Repository — provider-free source control.");
 useEffect(()=>{apiFetch("/repositories/").then(r=>r.json()).then(d=>{if(Array.isArray(d)){setRepos(d);if(d[0])setSelected(String(d[0].id));}}).catch(e=>setMessage(e.message))},[]);
 async function create(){if(!name.trim()||busy)return;setBusy(true);try{const r=await apiFetch("/repositories/",{method:"POST",body:JSON.stringify({name:name.trim(),files:workspace?.files||{"README.md":"# Developer OS Repository\n"}})});const d=await r.json();if(!r.ok)throw Error(d.error||"Repository creation failed");setRepos(x=>[d,...x]);setSelected(String(d.id));setName("");setMessage("Independent repository created.");}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function action(type){if(!selected||!workspace||busy)return;setBusy(true);try{const r=await apiFetch(`/repositories/${selected}/${type}/`,{method:"POST",body:JSON.stringify({workspace_id:workspace.id,message:"Workspace update"})});const d=await r.json();if(!r.ok)throw Error(d.error||`${type} failed`);setMessage(type==="push"?"Committed to Developer OS Repository.":"Pulled from Developer OS Repository.");onSync?.(type==="push"?"push":"pull");}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="dos-source-control"><header><div><strong>SOURCE CONTROL</strong><small>DEVELOPER OS NATIVE REPOSITORY</small></div><button onClick={onClose}>×</button></header><div className="dos-source-body"><label>Repository<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select repository</option>{repos.map(r=><option key={r.id} value={r.id}>{r.name} · {r.branch}</option>)}</select></label><div className="dos-source-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New repository name"/><button onClick={create} disabled={busy}>＋ Create</button></div><div className="dos-source-actions"><button onClick={()=>action("push")} disabled={!selected||busy}>↑ Commit / Push</button><button onClick={()=>action("pull")} disabled={!selected||busy}>↓ Pull</button></div><p>{message}</p><div className="dos-source-note">No GitHub account. No external remote. Your repository is stored and versioned inside Developer OS.</div></div></section>
}
