import * as monaco from "monaco-editor";
import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../services/api";

export function GlobalSearch({ workspace, files, onOpen, onClose, onFileSaved }) {
  const [query,setQuery]=useState("");
  const [replace,setReplace]=useState("");
  const [caseSensitive,setCaseSensitive]=useState(false);
  const [regex,setRegex]=useState(false);
  const [replaceMode,setReplaceMode]=useState(false);
  const results=useMemo(()=>{if(!workspace||!query)return [];let re;try{re=regex?new RegExp(query,caseSensitive?"g":"gi"):new RegExp(query.replace(/[.*+?^$()|[\\]\\]/g,"\\$&"),caseSensitive?"g":"gi")}catch{return []}const out=[];Object.entries(files||{}).forEach(([path,text])=>String(text).split("\n").forEach((line,i)=>{re.lastIndex=0;let m;while((m=re.exec(line))){out.push({path,line:i+1,text:line.trim(),column:m.index+1,match:m[0]});if(!re.global)break;if(m[0]==="")re.lastIndex++}}));return out.slice(0,500);  },[files,query,regex,caseSensitive,workspace]);
  async function applyReplace(all=false){if(!query||!results.length||!workspace)return;let rx;try{rx=regex?new RegExp(query,caseSensitive?"g":"gi"):new RegExp(query.replace(/[.*+?^$()|[\\]\\]/g,"\\$&"),caseSensitive?"g":"gi")}catch{return}const targets=all?[...new Set(results.map(r=>r.path))]:[results[0].path];if(all&&!window.confirm(`Replace ${results.length} matches in ${targets.length} files?`))return;let revision=workspace.revision;const next={...files};try{for(const path of targets){const content=String(next[path]||"").replace(rx,replace);const resp=await apiFetch(`/ide/workspaces/${workspace.id}/files/`,{method:"POST",body:JSON.stringify({path,content,revision})});const d=await resp.json();if(!resp.ok)throw Error(d.error||d.detail||("Replace failed for "+path));next[path]=content;revision=d.revision??revision;onFileSaved?.(path,content,revision)}setQuery("");}catch(e){alert(e.message||"Replace failed");}}
  return <div className="dos-search-panel"><div className="dos-search-head"><strong>SEARCH</strong><span className="dos-search-count">{results.length}</span><button onClick={onClose}>×</button></div><div className="dos-search-input"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search in workspace…"/><button className={caseSensitive?"on":""} onClick={()=>setCaseSensitive(x=>!x)}>Aa</button><button className={regex?"on":""} onClick={()=>setRegex(x=>!x)}>.*</button></div><div className="dos-search-tabs"><button className={!replaceMode?"active":""} onClick={()=>setReplaceMode(false)}>Find</button><button className={replaceMode?"active":""} onClick={()=>setReplaceMode(true)}>Replace</button></div>{replaceMode&&<div className="dos-search-input"><span>↪</span><input value={replace} onChange={e=>setReplace(e.target.value)} placeholder="Replace with…"/><button onClick={()=>applyReplace(false)}>Replace</button><button onClick={()=>applyReplace(true)}>All</button></div>}<div className="dos-search-meta">{results.length} result{results.length===1?"":"s"}</div><div className="dos-search-results">{results.map((r,i)=><button key={`${r.path}:${r.line}:${i}`} onClick={()=>onOpen(r.path,r.line,r.column)}><strong>{r.path}</strong><span><b>{r.line}</b> {r.text||"(empty line)"}</span></button>)}</div></div>
}

export function ProblemsPanel({ diagnostics=[], onClose, onOpen }) {
 return <section className="dos-problems"><header><strong>PROBLEMS</strong><span>{diagnostics.length}</span><button onClick={onClose}>×</button></header>{diagnostics.length?<div>{diagnostics.map((d,i)=><button key={i} onClick={()=>onOpen?.(d)}><i className={d.severity||"error"}/><span><b>{d.path||"Current file"}</b><small>Line {d.line||1}:{d.column||1} — {d.message}</small></span></button>)}</div>:<p>✓ No problems detected.</p>}</section>
}

export function RunCenter({workspace,files,onClose}) {
 const [command,setCommand]=useState("npm run build"),[running,setRunning]=useState(false),[output,setOutput]=useState(""),[exitCode,setExitCode]=useState(null),[duration,setDuration]=useState(0),[tab,setTab]=useState("terminal"),[processes,setProcesses]=useState([]),[busy,setBusy]=useState(false);
 const presets=[["Build","npm run build"],["Test","npm test"],["Lint","npm run lint"],["Python","python main.py"],["Django","python manage.py check"],["TypeScript","npx tsc --noEmit"]];
 async function execute(){if(!workspace||running||!command.trim())return;setRunning(true);setExitCode(null);setOutput("");setTab("terminal");const started=performance.now();try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/execute/`,{method:"POST",body:JSON.stringify({command:command.trim(),files:files||workspace.files||{}})});const d=await r.json();if(!r.ok)throw Error(d.error||"Secure runner unavailable");setOutput([d.stdout,d.stderr].filter(Boolean).join("\\n"));setExitCode(d.exit_code??null);setDuration(d.duration_ms||Math.round(performance.now()-started));}catch(e){setOutput(e.message);setExitCode(-1)}finally{setRunning(false)}}
 async function refreshProcesses(){if(!workspace)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/processes/`);const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Process API unavailable (HTTP ${r.status})`);setProcesses(Array.isArray(d)?d:(d.processes||[]))}catch(e){setOutput(e.message||"Process API unavailable")}finally{setBusy(false)}}
 async function startProcess(){if(!workspace||busy||!command.trim())return;setBusy(true);setOutput("");try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/process/start/`,{method:"POST",body:JSON.stringify({command:command.trim(),files:files||workspace.files||{}})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Process start failed (HTTP ${r.status})`);setOutput([d.stdout,d.stderr].filter(Boolean).join("\n")||`Process ${d.id||""} started.`);setTab("processes");await refreshProcesses()}catch(e){setOutput(e.message||"Process start failed")}finally{setBusy(false)}}
 async function stopProcess(id){if(!workspace||!id)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/process/${encodeURIComponent(id)}/stop/`,{method:"POST"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||d.detail||`Process stop failed (HTTP ${r.status})`);await refreshProcesses()}catch(e){setOutput(e.message||"Process stop failed")}finally{setBusy(false)}}
 useEffect(()=>{refreshProcesses();const t=setInterval(refreshProcesses,4000);return()=>clearInterval(t)},[workspace?.id]);
 return <section className="dos-run-center"><header><div><strong>CODE EXECUTION</strong><small>SECURE SANDBOX · BUILD · TEST · DEBUG</small></div><button onClick={onClose}>×</button></header><div className="dos-run-presets">{presets.map(([name,cmd])=><button key={name} onClick={()=>setCommand(cmd)}>{name}</button>)}</div><div className="dos-run-command"><span>›</span><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")execute()}}/><button className="dos-run-main" onClick={execute} disabled={running||busy}>{running?"■ Running…":"▶ Run"}</button><button onClick={startProcess} disabled={running||busy||!command.trim()}>⚙ Start Process</button></div><div className="dos-run-tabs"><button className={tab==="terminal"?"active":""} onClick={()=>setTab("terminal")}>TERMINAL</button><button className={tab==="processes"?"active":""} onClick={()=>setTab("processes")}>PROCESSES {processes.length}</button><button onClick={refreshProcesses}>↻</button></div>{tab==="terminal"?<div className="dos-run-output"><div className="dos-run-metrics"><span>STATUS <b>{running?"RUNNING":exitCode===0?"SUCCESS":exitCode===null?"READY":"FAILED"}</b></span><span>EXIT <b>{exitCode??"—"}</b></span><span>TIME <b>{duration}ms</b></span><span>RUNTIME <b>ISOLATED</b></span></div><pre>{output||"Ready. Code executes in the configured Developer OS runner, not in the browser."}</pre></div>:<div className="dos-process-list">{processes.length?processes.map((p,i)=><div className="dos-process" key={p.id||p.process_id||i}><div><b>{p.command||p.name||"process"}</b><small>{p.id||p.process_id} · {p.status||"running"}</small></div><button onClick={()=>stopProcess(p.id||p.process_id)} disabled={busy}>Stop</button></div>):<div className="dos-empty">No active processes.</div>}</div>}<footer><span>🔒 Sandbox execution · resource limits enforced by runner</span><button onClick={()=>setTab("processes")}>Manage processes</button></footer></section>
}
export function DebuggerPanel({workspace,activeFile,onOpen,onClose}) {
 const [session,setSession]=useState(null),[state,setState]=useState("idle"),[breakpoints,setBreakpoints]=useState([]),[expression,setExpression]=useState(""),[result,setResult]=useState(null),[stack,setStack]=useState([]),[scopes,setScopes]=useState([]),[variables,setVariables]=useState([]),[output,setOutput]=useState(""),[busy,setBusy]=useState(false),[line,setLine]=useState(1),[polling,setPolling]=useState(false);
 async function call(action,extra={}){if(!workspace)return;setBusy(true);try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/debug/`,{method:"POST",body:JSON.stringify({action,session_id:session,path:activeFile,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||"Debugger request failed");setSession(d.session_id||session);setState(d.state||state);setStack(d.stack||[]);setScopes(d.scopes||[]);setVariables(d.variables||[]);setOutput(d.output||"");setResult(d.result??null);if(d.breakpoints)setBreakpoints(d.breakpoints);return d}catch(e){setOutput(e.message||"Debugger request failed")}finally{setBusy(false)}}
 useEffect(()=>{if(!session||!workspace)return;setPolling(true);const timer=setInterval(async()=>{try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/debug/`,{method:"POST",body:JSON.stringify({action:"status",session_id:session})});const d=await r.json();if(r.ok){setState(d.state||"idle");setStack(d.stack||[]);setBreakpoints(d.breakpoints||[]);}}catch(e){setOutput(e?.message||"Debugger status unavailable");}},1000);return()=>{clearInterval(timer);setPolling(false)}},[session,workspace?.id]);
 function toggleBreakpoint(){if(!activeFile)return;const existing=breakpoints.find(b=>b.path===activeFile&&Number(b.line)===Number(line));call(existing?"remove_breakpoint":"set_breakpoint",{path:activeFile,line:Number(line)});}
 return <section className="dos-debugger"><header><div><strong>DEBUGGER</strong><small>{state.toUpperCase()} · LIVE DAP</small></div><button onClick={onClose}>×</button></header><div className="dos-debug-toolbar"><button onClick={()=>call("start",{path:activeFile,line:Number(line)})} disabled={busy||!activeFile}>▶ Start</button><button onClick={()=>call("continue")} disabled={!session||busy}>Continue</button><button onClick={()=>call("pause")} disabled={!session||busy}>Pause</button><button onClick={()=>call("step_over")} disabled={!session||busy}>Step Over</button><button onClick={()=>call("step_into")} disabled={!session||busy}>Step Into</button><button onClick={()=>call("step_out")} disabled={!session||busy}>Step Out</button><button onClick={()=>call("stop")} disabled={!session||busy}>■ Stop</button></div>
 <div className="dos-debug-breakpoint-bar"><span>Breakpoint line</span><input type="number" min="1" value={line} onChange={e=>setLine(Math.max(1,Number(e.target.value)||1))}/><button onClick={toggleBreakpoint} disabled={!activeFile||busy}>{breakpoints.some(b=>b.path===activeFile&&Number(b.line)===Number(line))?"Remove":"Set"} Breakpoint</button><span className="dos-debug-live">{polling?"● Live":"○ Idle"}</span></div>
 <div className="dos-debug-grid"><div><h4>CALL STACK</h4>{stack.length?stack.map((f,i)=><button key={i} onClick={()=>onOpen?.(f.source?.path||f.path,f.line,f.column)}><strong>{f.name||"frame"}</strong><small>{f.source?.path||f.path||"unknown"}:{f.line||1}</small></button>):<p>Start debugging to inspect the live stack.</p>}</div>
 <div><h4>SCOPES / VARIABLES</h4>{scopes.map((s,i)=><div key={i} className="dos-debug-scope"><b>{s.name}</b><small>{s.variablesReference?"variables available":"empty scope"}</small></div>)}{variables.length?variables.map((v,i)=><div className="dos-debug-var" key={i}><b>{v.name}</b><span>{String(v.value??"")}</span><small>{v.type||""}</small></div>):<p>No variables loaded for current frame.</p>}</div>
 <div><h4>BREAKPOINTS</h4>{breakpoints.length?breakpoints.map((b,i)=><button key={i} onClick={()=>onOpen?.(b.path,b.line,b.column)}><span>{b.verified?"●":"○"} {b.path}</span><small>line {b.line}{b.message?" · "+b.message:""}</small></button>):<p>No breakpoints.</p>}</div></div>
 <div className="dos-debug-console"><div><b>DEBUG CONSOLE</b><button onClick={()=>call("evaluate",{expression})} disabled={!session||busy||!expression.trim()}>Evaluate</button></div><input value={expression} onChange={e=>setExpression(e.target.value)} onKeyDown={e=>e.key==="Enter"&&call("evaluate",{expression})} placeholder="Evaluate expression in current frame…"/>{result!==null&&<pre>{typeof result==="string"?result:JSON.stringify(result,null,2)}</pre>}{output&&<pre>{output}</pre>}</div></section>
}
export function PreviewPanel({workspace,onClose}) {
 const [url,setUrl]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function start(){if(!workspace)return;setLoading(true);setError("");try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/preview/start/`,{method:"POST",body:JSON.stringify({framework:workspace.framework||""})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||`Preview start failed (HTTP ${r.status})`);setUrl(d.public_preview||d.preview_url||d.url||"")}catch(e){setError(e.message||"Preview could not be started")}finally{setLoading(false)}}
 return <div className="dos-preview"><header><strong>LIVE PREVIEW</strong><button onClick={onClose}>×</button></header><div className="dos-preview-toolbar"><button onClick={start}>{loading?"Starting…":"▶ Start Preview"}</button><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Preview path"/><button onClick={()=>url&&window.open(url,"_blank","noopener,noreferrer")}>↗</button></div>{error&&<div className="dos-preview-empty">{error}</div>}{url&&!error&&<div className="dos-preview-empty">Preview process started. Open the preview path in the authenticated Developer OS session.</div>}{!url&&!error&&<div className="dos-preview-empty">Start a workspace preview to launch the configured framework runner.</div>}</div>
}

export function SourceControlPanel({workspace,onClose,onSync}) {
 const [repos,setRepos]=useState([]),[name,setName]=useState(""),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("Source control ready."),[git,setGit]=useState({}),[commitMessage,setCommitMessage]=useState("Workspace update"),[branch,setBranch]=useState("");
 useEffect(()=>{apiFetch("/repositories/").then(r=>r.json()).then(d=>{if(Array.isArray(d)){setRepos(d);if(d[0])setSelected(String(d[0].id));}}).catch(e=>setMessage(e.message))},[]);
 async function gitFileAction(operation,path){
  if(!workspace?.id||busy||!path)return;
  if(operation==="discard"&&!window.confirm("Discard changes for "+path+"?"))return;
  setBusy(true);
  try{
   const r=await apiFetch(`/ide/workspaces/${workspace.id}/git/file/`,{method:"POST",body:JSON.stringify({operation,path})});
   const d=await r.json();if(!r.ok)throw Error(d.error||"Git file operation failed");
   setMessage(operation+" completed for "+path);await refresh();
  }catch(e){setMessage(e.message)}finally{setBusy(false)}
 }
 async function gitAction(operation,args,force=false){
  if(!workspace?.id||(busy&&!force))return;
  setBusy(true);
  try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/git/`,{method:"POST",body:JSON.stringify({operation,args})});const d=await r.json();if(!r.ok)throw Error(d.error||"Git operation failed");setGit(x=>({...x,[operation]:d}));setMessage(operation+" completed.");return d}catch(e){setMessage(e.message)}finally{setBusy(false)}
 }
 async function openDiff(file,original,modified){
  try{
   const left=monaco.editor.createModel(original||"");
   const right=monaco.editor.createModel(modified||"");
   const container=document.createElement("div");container.style.cssText="position:fixed;inset:8%;z-index:9999;background:#111827;border:1px solid #374151;border-radius:10px;box-shadow:0 20px 60px rgba(0,0,0,.5)";
   document.body.appendChild(container);
   const header=document.createElement("div");header.style.cssText="height:42px;padding:10px 14px;color:#fff;font-weight:600";
   header.textContent="Diff · "+file+"   ×";header.onclick=()=>{editor.dispose();left.dispose();right.dispose();container.remove()};
   container.appendChild(header);
   const host=document.createElement("div");host.style.cssText="position:absolute;top:42px;left:0;right:0;bottom:0";container.appendChild(host);
   const editor=monaco.editor.createDiffEditor(host,{readOnly:true,automaticLayout:true,renderSideBySide:true});
   editor.setModel({original:left,modified:right});
  }catch{}
 }
 async function refresh(){await Promise.all([gitAction("status",["status","--short"],true),gitAction("diff",["diff"],true),gitAction("files",["diff","--name-only"],true),gitAction("branches",["branch","--list"],true),gitAction("log",["log","-20","--oneline"],true)])}
 async function create(){if(!name.trim()||busy)return;setBusy(true);try{const r=await apiFetch("/repositories/",{method:"POST",body:JSON.stringify({name:name.trim(),files:workspace?.files||{"README.md":"# Developer OS Repository\n"}})});const d=await r.json();if(!r.ok)throw Error(d.error||"Repository creation failed");setRepos(x=>[d,...x]);setSelected(String(d.id));setName("");setMessage("Independent repository created.");}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function nativeCommit(){const msg=commitMessage.trim();if(!msg)return setMessage("Commit message is required.");await gitAction("commit",["add","-A"]);await gitAction("commit",["commit","-m",msg]);await refresh();}
 async function checkoutBranch(){
  const b=branch.trim();
  if(!b||busy)return;
  if(!/^[A-Za-z0-9._\/-]{1,120}$/.test(b))return setMessage("Invalid branch name.");
  if(!window.confirm("Switch workspace to branch "+b+"?"))return;
  setBusy(true);
  try{
   const r=await apiFetch(`/ide/workspaces/${workspace.id}/git/`,{method:"POST",body:JSON.stringify({operation:"checkout",args:["checkout",b]})});
   const d=await r.json();if(!r.ok)throw Error(d.error||"Branch checkout failed");
   setMessage("Switched to "+b);setBranch("");await refresh();
  }catch(e){setMessage(e.message)}finally{setBusy(false)}
 }
 async function nativeBranch(){const b=branch.trim();if(!b)return setMessage("Branch name is required.");await gitAction("branch",["checkout","-b",b]);setBranch("");await refresh();}
 async function action(type){if(!selected||!workspace||busy)return;setBusy(true);try{const r=await apiFetch(`/repositories/${selected}/${type}/`,{method:"POST",body:JSON.stringify({workspace_id:workspace.id,message:commitMessage||"Workspace update"})});const d=await r.json();if(!r.ok)throw Error(d.error||`${type} failed`);setMessage(type==="push"?"Committed to Developer OS Repository.":"Pulled from Developer OS Repository.");onSync?.(type==="push"?"push":"pull");}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="dos-source-control"><header><div><strong>SOURCE CONTROL</strong><small>GIT WORKTREE · NATIVE REPOSITORY</small></div><button onClick={onClose}>×</button></header><div className="dos-source-body">
  <div className="dos-source-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New repository name"/><button onClick={create} disabled={busy}>＋ Create</button><button onClick={refresh} disabled={busy}>↻ Refresh</button></div>
  <label>Developer OS Repository<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select repository</option>{repos.map(r=><option key={r.id} value={r.id}>{r.name} · {r.branch}</option>)}</select></label>
  <div className="dos-source-create"><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="new branch name"/><button onClick={nativeBranch} disabled={busy}>＋ Branch</button><button onClick={checkoutBranch} disabled={busy}>⇄ Checkout</button></div>
  <div className="dos-source-create"><input value={commitMessage} onChange={e=>setCommitMessage(e.target.value)} placeholder="Commit message"/><button onClick={nativeCommit} disabled={busy}>✓ Commit</button></div>
  <div className="dos-source-actions"><button onClick={()=>action("push")} disabled={!selected||busy}>↑ Repository Push</button><button onClick={()=>action("pull")} disabled={!selected||busy}>↓ Repository Pull</button></div>
  <div className="dos-source-actions"><button onClick={()=>gitAction("status",["status"])} disabled={busy}>Status</button><button onClick={()=>gitAction("diff",["diff"])} disabled={busy}>Diff</button><button onClick={()=>gitAction("files",["diff","--name-only"])} disabled={busy}>Changed Files</button><button onClick={()=>gitAction("restore",["restore","."])} disabled={busy}>Restore Worktree</button><button onClick={()=>gitAction("branches",["branch","--list"])} disabled={busy}>Branches</button><button onClick={()=>gitAction("log",["log","-20","--oneline"])} disabled={busy}>Log</button></div>
  <p>{message}</p>
  <pre className="dos-source-output">{git.status?.stdout||git.status?.output||"No status loaded."}</pre>  <div className="dos-source-files">{String(git.files?.stdout||"").split(/\\r?\\n/).filter(Boolean).map((file,index)=><div key={file+index} className="dos-source-file"><code>{file}</code><span><button onClick={()=>gitFileAction("stage",file.trim())} disabled={busy}>Stage</button><button onClick={()=>gitFileAction("unstage",file.trim())} disabled={busy}>Unstage</button><button onClick={()=>gitFileAction("discard",file.trim())} disabled={busy}>Discard</button><button onClick={async()=>{try{const r=await apiFetch(`/ide/workspaces/${workspace.id}/git/file/`,{method:"POST",body:JSON.stringify({operation:"diff",path:file.trim()})});const d=await r.json();openDiff(file.trim(),"HEAD",d.stdout||d.output||"")}catch{}}} disabled={busy}>Diff</button></span></div>)}</div>
  <pre className="dos-source-output">{git.diff?.stdout||git.diff?.output||"No diff loaded."}</pre><button onClick={()=>{const raw=git.diff?.stdout||"";openDiff("workspace diff","",raw)}} disabled={!git.diff}>Open Monaco Diff</button><pre className="dos-source-output">{git.files?.stdout||git.files?.output||"No changed-file list loaded."}</pre>
  <pre className="dos-source-output">{git.branches?.stdout||git.branches?.output||"No branches loaded."}</pre>
  <pre className="dos-source-output">{git.log?.stdout||git.log?.output||"No history loaded."}</pre>
 </div></section>
}
