import { useEffect, useRef } from "react";
import * as monaco from "monaco-editor";
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker";
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker";
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker";
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker";
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker";

globalThis.MonacoEnvironment={getWorker(_id,label){if(label==="json")return new jsonWorker();if(["css","scss","less"].includes(label))return new cssWorker();if(["html","handlebars","razor"].includes(label))return new htmlWorker();if(["typescript","javascript"].includes(label))return new tsWorker();return new editorWorker()}};
monaco.languages.typescript.javascriptDefaults.setEagerModelSync(true);monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);
const compiler={target:monaco.languages.typescript.ScriptTarget.ES2022,allowNonTsExtensions:true,module:monaco.languages.typescript.ModuleKind.ESNext,moduleResolution:monaco.languages.typescript.ModuleResolutionKind.NodeJs,jsx:monaco.languages.typescript.JsxEmit.ReactJSX,allowJs:true,checkJs:false,strict:false};
monaco.languages.typescript.javascriptDefaults.setCompilerOptions(compiler);monaco.languages.typescript.typescriptDefaults.setCompilerOptions(compiler);
const extraLibs={
  javascript:[{content:'declare const process: any; declare const Buffer: any;'}],
  typescript:[{content:'declare const process: any; declare const Buffer: any;'}]
};
monaco.languages.typescript.javascriptDefaults.addExtraLib(extraLibs.javascript[0].content,"file:///developer-os/global.d.ts");
monaco.languages.typescript.typescriptDefaults.addExtraLib(extraLibs.typescript[0].content,"file:///developer-os/global.d.ts");

monaco.editor.defineTheme("developer-os-dark",{base:"vs-dark",inherit:true,rules:[{token:"comment",foreground:"61768b"},{token:"keyword",foreground:"57dfff"},{token:"string",foreground:"8ee6b5"},{token:"number",foreground:"d9a7ff"}],colors:{"editor.background":"#060b12","editor.foreground":"#d8eaff","editorLineNumber.foreground":"#385168","editorLineNumber.activeForeground":"#65e6ff","editorCursor.foreground":"#55e8ff","editor.selectionBackground":"#174363","editor.lineHighlightBackground":"#091725","editorIndentGuide.background1":"#102335","editorIndentGuide.activeBackground1":"#24455e","editorWidget.background":"#0b1622","editorWidget.border":"#1c3c55","editorSuggestWidget.background":"#0a1420","editorSuggestWidget.border":"#244b63","editorSuggestWidget.selectedBackground":"#12364c","editorHoverWidget.background":"#0b1622","editorHoverWidget.border":"#28516a","editorOverviewRuler.border":"#00000000"}});
const lang=p=>({js:"javascript",jsx:"javascript",ts:"typescript",tsx:"typescript",py:"python",html:"html",htm:"html",css:"css",scss:"scss",json:"json",md:"markdown",yaml:"yaml",yml:"yaml",sql:"sql",sh:"shell",bash:"shell",go:"go",rs:"rust",java:"java",php:"php",xml:"xml",vue:"html",c:"c",cpp:"cpp",h:"cpp",hpp:"cpp",txt:"plaintext",env:"plaintext"}[p.split(".").pop()?.toLowerCase()]||"plaintext");

export default function MonacoEditor({path,value,onChange,onCursorChange,diagnostics=[],remoteCursors=[]}){
 const host=useRef(null),editor=useRef(null),model=useRef(null),change=useRef(onChange),cursor=useRef(onCursorChange),pathRef=useRef(path),remoteDecorations=useRef([]),completion=useRef(null),models=useRef(new Map()),viewStates=useRef(new Map());
 useEffect(()=>{change.current=onChange;cursor.current=onCursorChange},[onChange,onCursorChange]);
 useEffect(()=>{if(!host.current)return;const ed=monaco.editor.create(host.current,{model:null,theme:"developer-os-dark",automaticLayout:true,minimap:{enabled:true},minimap:{enabled:true,side:"right",showSlider:"mouseover",renderCharacters:false},fontFamily:"JetBrains Mono, Consolas, monospace",fontSize:13,lineHeight:21,tabSize:2,insertSpaces:true,wordWrap:"off",smoothScrolling:true,cursorBlinking:"smooth",cursorSmoothCaretAnimation:"on",bracketPairColorization:{enabled:true},guides:{indentation:true,bracketPairs:true},folding:true,foldingStrategy:"auto",stickyScroll:{enabled:true},renderWhitespace:"selection",scrollBeyondLastLine:false,padding:{top:10,bottom:18},quickSuggestions:{other:true,comments:false,strings:true},suggestOnTriggerCharacters:true,parameterHints:{enabled:true},formatOnPaste:true,formatOnType:true,contextmenu:true,multiCursorModifier:"ctrlCmd",mouseWheelZoom:true,overviewRulerBorder:false,scrollbar:{verticalScrollbarSize:10,horizontalScrollbarSize:10,useShadows:false},find:{addExtraSpaceOnTop:true,autoFindInSelection:"never"},occurrencesHighlight:"singleFile",selectionHighlight:true,renderLineHighlight:"all",fixedOverflowWidgets:true,stickyScroll:{enabled:true},smoothScrolling:true,scrollBeyondLastLine:false,linkedEditing:true,bracketPairColorization:{enabled:true},guides:{bracketPairs:true,highlightActiveBracketPair:true},suggest:{showMethods:true,showFunctions:true,showConstructors:true},quickSuggestions:{other:true,comments:true,strings:true},parameterHints:{enabled:true},hover:{enabled:true},inlayHints:{enabled:"on"},codeLens:true});editor.current=ed;
 const c=ed.onDidChangeModelContent(()=>change.current?.(ed.getValue()));
 const p=ed.onDidChangeCursorPosition(e=>cursor.current?.({line:e.position.lineNumber,column:e.position.column,path:pathRef.current}));
 const format=ed.addAction({id:"developer-os.format-document",label:"Developer OS: Format Document",keybindings:[monaco.KeyMod.Shift|monaco.KeyMod.Alt|monaco.KeyCode.KeyF],run:async e=>{try{await e.getAction("editor.action.formatDocument")?.run()}catch{}}});
 const explain=ed.addAction({id:"developer-os.explain-selection",label:"Developer OS: Explain Selection",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyMod.Shift|monaco.KeyCode.KeyE],run:e=>{const s=e.getSelection();const text=s?e.getModel()?.getValueInRange(s):"";window.dispatchEvent(new CustomEvent("developer-os:ai-action",{detail:{action:"explain",path:pathRef.current,code:text||e.getValue()}}));}});
 const fix=ed.addAction({id:"developer-os.fix-selection",label:"Developer OS: Fix Selection",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyK],run:e=>{const s=e.getSelection();window.dispatchEvent(new CustomEvent("developer-os:ai-action",{detail:{action:"fix",path:pathRef.current,code:s?e.getModel()?.getValueInRange(s):e.getValue()}}));}});
 const completionAction=ed.addAction({id:"developer-os.ai-complete",label:"Developer OS: AI Complete",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.Space],run:e=>{window.dispatchEvent(new CustomEvent("developer-os:ai-action",{detail:{action:"complete",path:pathRef.current,code:e.getValue(),position:e.getPosition()}}));}});
 const duplicate=ed.addAction({id:"developer-os.duplicate-line",label:"Developer OS: Duplicate Line",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyD],run:e=>{const s=e.getSelection();if(!s)return;e.executeEdits("developer-os",[{range:s,text:e.getModel()?.getValueInRange(s)+"\n",forceMoveMarkers:true}]);}});
const gotoLine=ed.addAction({id:"developer-os.goto-line",label:"Developer OS: Go to Line",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyL],run:e=>{const p=e.getPosition();if(p)e.revealPositionInCenter(p);e.focus();}});
 const foldAll=ed.addAction({id:"developer-os.fold-all",label:"Developer OS: Fold All",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyMod.Shift|monaco.KeyCode.BracketLeft],run:e=>e.getAction("editor.foldAll")?.run()});
 const unfoldAll=ed.addAction({id:"developer-os.unfold-all",label:"Developer OS: Unfold All",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyMod.Shift|monaco.KeyCode.BracketRight],run:e=>e.getAction("editor.unfoldAll")?.run()});
const symbolOutline=ed.addAction({id:"developer-os.symbol-outline",label:"Developer OS: Show Symbol Outline",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyO],run:e=>{e.getAction("editor.action.quickOutline")?.run();e.focus();}});
 const focusBreadcrumb=ed.addAction({id:"developer-os.focus-breadcrumbs",label:"Developer OS: Focus Breadcrumbs",keybindings:[monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyB],run:e=>{e.getAction("breadcrumbs.focus")?.run();e.focus();}});
 const renameSelection=ed.addAction({id:"developer-os.rename-symbol",label:"Developer OS: Rename Symbol",keybindings:[monaco.KeyCode.F2],run:e=>{e.getAction("editor.action.rename")?.run();}});
 const references=ed.addAction({id:"developer-os.find-references",label:"Developer OS: Find References",keybindings:[monaco.KeyMod.Shift|monaco.KeyCode.F12],run:e=>{e.getAction("editor.action.referenceSearch.trigger")?.run();}});
  return()=>{c.dispose();p.dispose();format.dispose();duplicate.dispose();explain.dispose();fix.dispose();completionAction.dispose();gotoLine.dispose();foldAll.dispose();unfoldAll.dispose();symbolOutline.dispose();focusBreadcrumb.dispose();renameSelection.dispose();references.dispose();for(const m of models.current.values())if(!m.isDisposed())m.dispose();models.current.clear();viewStates.current.clear();ed.dispose();editor.current=null;model.current=null}},[]);
 useEffect(()=>{const ed=editor.current;if(!ed)return;const normalized=path||"untitled";const previous=pathRef.current;if(previous&&ed.getModel()===model.current){viewStates.current.set(previous,ed.saveViewState());}pathRef.current=normalized;const uri=monaco.Uri.parse(`inmemory://developer-os/${encodeURIComponent(normalized)}`);let next=models.current.get(normalized);if(!next||next.isDisposed()){next=monaco.editor.getModel(uri)||monaco.editor.createModel(value||"",lang(normalized),uri);models.current.set(normalized,next);}else{monaco.editor.setModelLanguage(next,lang(normalized));}if(next.getValue()!==(value||"")&&!ed.hasTextFocus())next.setValue(value||"");if(ed.getModel()!==next)ed.setModel(next);model.current=next;const saved=viewStates.current.get(normalized);if(saved)ed.restoreViewState(saved);ed.focus();return()=>{if(model.current===next)model.current=null}},[path]);
 useEffect(()=>{const m=model.current;if(m&&m.getValue()!==(value||"")&&!editor.current?.hasTextFocus())m.setValue(value||"")},[value]);
 useEffect(()=>{const m=model.current;if(!m)return;const markers=(diagnostics||[]).filter(x=>!x.path||x.path===path).map(x=>({startLineNumber:Math.max(1,x.line||1),endLineNumber:Math.max(1,x.end_line||x.line||1),startColumn:Math.max(1,x.column||1),endColumn:Math.max(2,x.end_column||((x.column||1)+1)),message:x.message||"Diagnostic",severity:x.severity==="warning"?monaco.MarkerSeverity.Warning:x.severity==="info"?monaco.MarkerSeverity.Info:monaco.MarkerSeverity.Error}));monaco.editor.setModelMarkers(m,"developer-os",markers);return()=>monaco.editor.setModelMarkers(m,"developer-os",[])},[diagnostics,path]);

 useEffect(()=>{const ed=editor.current;if(!ed)return;const dec=(remoteCursors||[]).filter(x=>x.cursor?.path===path||x.cursor?.file===path).map((x,i)=>{const line=Math.max(1,Number(x.cursor.line||1));const col=Math.max(1,Number(x.cursor.column||1));return {range:new monaco.Range(line,col,line,col),options:{className:"dos-remote-cursor",hoverMessage:{value:"**"+(x.username||"Developer")+"**"},afterContentClassName:"dos-remote-cursor-label",stickiness:monaco.editor.TrackedRangeStickiness.Never}}});remoteDecorations.current=ed.deltaDecorations(remoteDecorations.current,dec);return()=>{remoteDecorations.current=ed.deltaDecorations(remoteDecorations.current,[])}},[remoteCursors,path]);
 return <div ref={host} className="monaco-host" aria-label={`Developer OS code editor ${path||"untitled"}`}/>;
}


// Remote cursor decorations are lightweight Monaco decorations driven by collaboration presence.
